### ISSUE TITLE
Transport Error when connecting to Qdrant Cloud

### ISSUE THREAD

**Issue by justindgm** [qdrant/rust-client#170]
I have a cluster set up on Qdrant Cloud. When I click "code sample" in the UI and select rust, it gives me the following code:

```rust
use qdrant_client::Qdrant;

#[tokio::main]
async fn main() {
  let client = Qdrant::from_url("https://[cluster id].us-east4-0.gcp.cloud.qdrant.io:6334")
      .api_key("<your-token>")
      .build()
      .unwrap();
      
  let collections_list = client.list_collections().await;
  let _ = dbg!(collections_list);
}
```

When I run this exact code (substituting in the cluster id and my api key), I get the following output:

```bash
[src/main.rs:31:13] collections_list = Err(
    ResponseError {
        status: Status {
            code: Internal,
            message: "Failed to connect to https://[cluster id].us-east4-0.gcp.cloud.qdrant.io:6334/: transport error",
            source: None,
        },
    },
)
```

I have run this code both from my local machine (m3 max macbook pro) and from a remote ubuntu machine on GCP.

I have also run the following curl command from my local machine:

`curl -X GET "${QDRANT_CLUSTER_URL}:6333" -H "api-key: ${QDRANT_API_KEY}"`

And received a valid response. This leads me to believe that the issue is either grpc related or rust client related.

I've looked at some of the previous (closed) issues that dealt with connection issues, and it looks like they were mostly url typos. I've tried a number of variations to make sure that isn't the case here for me.

I am using the 1.10.2 version of the client, and my qdrant cloud cluster is running v1.10.1

**Comment by generall** [comment]
It looks like the bug is introduced in 1.10.2 with tonic upgrade. We will look into it ASAP, please try to use v1.10.1 meanwhile

**Comment by justindgm** [comment]
Can confirm that v1.10.1 works. Thank you.

**Comment by Anush008** [comment]
Fixed with https://github.com/qdrant/rust-client/releases/tag/v1.10.3.
