### ISSUE TITLE
Build with qdrant-client fails

### ISSUE THREAD

**Issue by rstropek** [qdrant/rust-client#18]
## How to reproduce

* Create a new Rust application: `cargo new test-qdrant-client`
* Add *qdrant-client* as specified in docs: `cargo add qdrant-client`
* Build app: `cargo build`

## Expected result

App builds successfully, prints *Hello World*

## Actual result

Build fails with message *Error: Custom { kind: Other, error: "protoc failed: collections.proto:73:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\n...*

## Environment

Identical behavior with *rust stable* (rustc 1.67.1) and *rust nightly* (rustc 1.69.0-nightly).

**Comment by MrBeeMovie** [comment]
I am having this same issue. Is anyone looking at this?

**Comment by agourlay** [comment]
I am unfortunately not able to reproduce this issue following the steps provided.
It must be due a local difference in our setup.

Which version of protoc do you have installed locally?

For me I have

```bash
protoc --version
libprotoc 3.12.4
```

**Comment by rstropek** [comment]
For me: `libprotoc 3.6.1`

**Comment by rstropek** [comment]
Updated *libprotoc*, is now `libprotoc 22.0`.

Error has changed:

```txt
Error: Custom { kind: Other, error: "protoc failed: google/protobuf/struct.proto: File not found.\npoints_service.proto:7:1: Import \"google/protobuf/struct.proto\" was not found or had errors.\ngoogle/protobuf/timestamp.proto: File not found.\nsnapshots_service.proto:5:1: Import \"google/protobuf/struct.proto\" was not found or had errors.\nsnapshots_service.proto:6:1: Import \"google/protobuf/timestamp.proto\" was not found or had errors.\nsnapshots_service.proto:59:3: \"google.protobuf.Timestamp\" is not defined.\nqdrant.proto:4:1: Import \"points_service.proto\" was not found or had errors.\nqdrant.proto:5:1: Import \"snapshots_service.proto\" was not found or had errors.\n" }
```

**Comment by agourlay** [comment]
Are you able to set a protoc version identical to mine to rule out compatibility issues?

**Comment by rstropek** [comment]
@agourlay Do you have a link to the version?

**Comment by rstropek** [comment]
Current status:

```
protoc --version
libprotoc 3.12.4
```

Result from `cargo build`:

```txt
Error: Custom { kind: Other, error: "protoc failed: google/protobuf/struct.proto: File not found.\npoints_service.proto:7:1: Import \"google/protobuf/struct.proto\" was not found or had errors.\ngoogle/protobuf/timestamp.proto: File not found.\nsnapshots_service.proto:5:1: Import \"google/protobuf/struct.proto\" was not found or had errors.\nsnapshots_service.proto:6:1: Import \"google/protobuf/timestamp.proto\" was not found or had errors.\nsnapshots_service.proto:59:3: \"google.protobuf.Timestamp\" is not defined.\nqdrant.proto:4:1: Import \"points_service.proto\" was not found or had errors.\nqdrant.proto:5:1: Import \"snapshots_service.proto\" was not found or had errors.\n" }
```

**Comment by rstropek** [comment]
I don't have *DOCS_RS* set.

**Comment by agourlay** [comment]
Are you running on Windows?

**Comment by agourlay** [comment]
Thank you for your patience and reactivity :pray: 

It looks like a `PATH` issue to me, the google/protobuf files should be available.

```bash
which protoc
/usr/bin/protoc
```

and then the extra library can be found in

```
/usr/include/google/protobuf
```

**Comment by rstropek** [comment]
```txt
09:39:49 rainer@DESKTOP-B6V5TGG system32 → ls /usr/include/google/protobuf
any.h                  empty.proto                       map_field.h           stubs
any.pb.h               extension_set.h                   map_field_inl.h       text_format.h
any.proto              field_mask.pb.h                   map_field_lite.h      timestamp.pb.h
api.pb.h               field_mask.proto                  map_type_handler.h    timestamp.proto
api.proto              generated_enum_reflection.h       message.h             type.pb.h
arena.h                generated_enum_util.h             message_lite.h        type.proto
arena_impl.h           generated_message_reflection.h    metadata.h            unknown_field_set.h
arenastring.h          generated_message_table_driven.h  metadata_lite.h       util
descriptor.h           generated_message_util.h          reflection.h          wire_format.h
descriptor.pb.h        has_bits.h                        reflection_ops.h      wire_format_lite.h
descriptor.proto       implicit_weak_message.h           repeated_field.h      wire_format_lite_inl.h
descriptor_database.h  inlined_string_field.h            service.h             wrappers.pb.h
duration.pb.h          io                                source_context.pb.h   wrappers.proto
duration.proto         map.h                             source_context.proto
dynamic_message.h      map_entry.h                       struct.pb.h
empty.pb.h             map_entry_lite.h                  struct.proto
09:40:00 rainer@DESKTOP-B6V5TGG system32 → which protoc
/usr/local/bin/protoc
09:40:10 rainer@DESKTOP-B6V5TGG system32 →
```

**Comment by agourlay** [comment]
Running out of ideas here sorry.

How did you install `protoc` in first place?

**Comment by rstropek** [comment]
Sorry, don't remember anymore. It would be nice if the Rust client's docs would contain the recommended steps to install protoc for the Qdrant client.

**Comment by agourlay** [comment]
Improving the documentation will definitely be the outcome of this issue :)

@rstropek I can propose you a debugging session together today, ping me arnaud.gourlay@qdrant.com if you are interested.

**Comment by rstropek** [comment]
@agourlay I have meetings all through the day today. Let's discuss a time for the debugging session when we meet today in the evening.

**Comment by agourlay** [comment]
Sounds good to me :+1:

**Comment by rstropek** [comment]
@agourlay I tried to repro the bug using the official Rust docker image. Inside a brand new Rust container, I ran `apt install -y protobuf-compiler`. After doing that, the Qdrant Rust client can successfully compile. However, I did the same on my machine (uninstall protoc, clean reinstall), still no luck.

That proves that the problem is with my setup. I will dive deeper and report the solution as soon as I found it.

**Comment by agourlay** [comment]
@rstropek alright, good luck with the investigation :+1: 

@MrBeeMovie do you have a similar setup?

**Comment by MrBeeMovie** [comment]
> @rstropek alright, good luck with the investigation 👍
> 
> @MrBeeMovie do you have a similar setup?

I am on Windows. I was able to fix by setting path for PROTOC env variable.

**Comment by rstropek** [comment]
For people having similar problems: For me, setting `PROTOC_INCLUDE` to `/usr/include` helped.

**Comment by mliljenberg** [comment]
Just adding this in case anyone else is having problems. I had the same problem as above that it would not build on WSL2 for Windows. 

Steps I took where:
1. Install the latest binary manually, the default install gave an old version.
2. Change `PROTOC` and `PROTOC_INCLUDE` env variables to point to the bin and the `/include` folder.
