### ISSUE TITLE
[bug] h2 protocol error: http2 error when running example

### ISSUE THREAD

**Issue by morristai** [qdrant/rust-client#188]
When running `examples/deprecated_search.rs` and `examples/search.rs` on localhost. It gives error: 

```bash
ResponseError { status: Status { code: Unknown, message: "h2 protocol error: http2 error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b"", FRAME_SIZE_ERROR, Library) }))) } }
```

On server side, it shows:

```bash
2024-09-25T20:40:00.830337Z ERROR actix_http::h1::dispatcher: stream error: request parse error: invalid HTTP version specified
```

Test Env: 
- OS: Ubuntu 24.04 / macOS 14.6.1
- Qdrant version: 1.11.5

**Comment by timvisee** [comment]
I cannot reproduce this problem.

Could you check whether it works when running the following two next to each other:

```bash
git clone git@github.com:qdrant/rust-client.git
cd rust-client
cargo run --example search
```

```bash
docker run --rm -it -p 6333:6333 -p 6334:6334 qdrant/qdrant:latest
```

What I'm seeing:

![image](https://github.com/user-attachments/assets/b463a0d1-ec33-4c1a-b9d6-47da95f36d19)

**Comment by morristai** [comment]
Oh, my apologies, the port is misconfigured. At first, I followed the Python client that uses port 6333 in the Qdrant main repository: 
<img width="944" alt="image" src="https://github.com/user-attachments/assets/df64c3a0-48dc-4e13-818d-4cf5b7cdf6e0">

It worked, but for the Rust client, it uses port 6334 for the gRPC port by default.

**Comment by timvisee** [comment]
No problem, happy to see you were able to fix it!

You're correct. The Python client uses the HTTP/REST API by default, while the Rust client uses gRPC which is on a different port.
