### ISSUE TITLE
Serde json support

### ISSUE THREAD

**Issue by MrBeeMovie** [qdrant/rust-client#19]
Please add serde json support. Serializing de-serializing payload is extremely painful right now. There is a Value class that is included but there is no support for serializing from json string. Why reinvent the wheel when you can use serde json to do all of that easily. The Value pattern is exactly what serde json already uses for unstructured json data.

**Comment by agourlay** [comment]
Would that work for your use case? https://github.com/qdrant/rust-client/pull/37

**Comment by agourlay** [comment]
fixed in https://github.com/qdrant/rust-client/releases/tag/v1.1.2

**Comment by diptanu** [comment]
This is amazing! @agourlay I was getting so frustrated as I was trying to build payloads lol
