### ISSUE TITLE
Docs: Mention that the Rust client explicitly needs port 6334 in URL for Qdrant cloud

### ISSUE THREAD

**Issue by rstropek** [qdrant/rust-client#20]
The cluster manager allows developers to copy a cluster's URL into the clipboard. That is convenient. If this URL is used with the Rust client, it does not work. It results in a 464 (incompatible protocol) error. As a developer, you have to add `:6334` to the URL to make it work. It would be helpful to have a hint in the cluster manager and/or the Rust client docs that this is important.

**Comment by agourlay** [comment]
Thank you for the suggestion :+1: 

I have added a paragraph regarding connecting to Qdrant cloud in https://github.com/qdrant/rust-client/commit/e36af145ad0eeb2c4ad220a74ee5edf1d6ad5243
