### ISSUE TITLE
Docs: Provided sample code does not work, outdated?

### ISSUE THREAD

**Issue by rstropek** [qdrant/rust-client#21]
The provided sample code in the [readme file](https://github.com/qdrant/rust-client#making-requests) does not work.

## Reproduction

* Create a new Rust app with `cargo new`
* Add all the necessary dependencies (e.g. *qdrant-client*, *tokio*, etc.)
* Copy the provided sample code from Qdrant Rust Client readme file
* Try to compile

## Result

Does not compile.

## Expected result

Compiles successfully.

**Comment by timvisee** [comment]
I noticed the same while giving this a spin.

I'll work on a PR to fix this.

**Comment by timvisee** [comment]
@rstropek I've fixed this in #22 and #23.

You can find the updated version here: https://github.com/timvisee/rust-client/blob/a1a21478ee068734b29714403588ccb38f91505c/README.md#making-requests
