### ISSUE TITLE
Cluster scaling API

### ISSUE THREAD

**Issue by ava57r** [qdrant/rust-client#32]
Hello!
Has not client supported cluster scaling API yet?

https://qdrant.tech/documentation/distributed_deployment/#cluster-scaling

**Comment by nilhex** [comment]
Follow the status: https://github.com/qdrant/rust-client/pull/33

**Comment by agourlay** [comment]
part of https://github.com/qdrant/rust-client/pull/45

**Comment by agourlay** [comment]
fixed in 1.2.0
