### ISSUE TITLE
In-Memory qdrant for tests

### ISSUE THREAD

**Issue by diptanu** [qdrant/rust-client#36]
Is it possible to start qdrant in-memory for testing? How do you guys test the client on CI?

**Comment by timvisee** [comment]
> Is it possible to start qdrant in-memory for testing?

This is currently not supported with the Rust client. The Python client does support ['Local mode'](https://github.com/qdrant/qdrant-client#local-mode) though.

> How do you guys test the client on CI?

CI invokes [`integration-tests.sh`](https://github.com/qdrant/rust-client/blob/master/tests/integration-tests.sh) to test the client. It ensures basic client functionality. The tests itself can be found [here](https://github.com/qdrant/rust-client/blob/da97b6ed5636c94cc871a5aa336a515343e6b675/src/lib.rs#L6-L144), for example.

**Comment by diptanu** [comment]
Thanks for pointing to the script, I think this approach should work for me as well. What CI do you guys use? Is there something which supports docker well?

**Comment by agourlay** [comment]
We simply use Github Action for this repo. https://github.com/qdrant/rust-client/blob/master/.github/workflows/test.yml.

**Comment by agourlay** [comment]
Closing issue as I believe the question was answered.

**Comment by jacobhq** [comment]
Is there any potential for this coming to the rust client in the future?

**Comment by agourlay** [comment]
Adding an in-memory version is currently not on the roadmap.
Having a complete feature parity is pretty expensive TBH and we prioritized Python for this use case.

**Comment by jacobhq** [comment]
Ok fair enough. Thanks though!
