### ISSUE TITLE
Error type checking

### ISSUE THREAD

**Issue by ava57r** [qdrant/rust-client#50]
Hi.
I see that you library uses anyhow lib for error handling.
Question.
Client has recoverable errors or all types of errors critical?

I am trying to check error when
- collection exists
- timeout expired

I get anyhow::Error and can not split these cases.

**Comment by Rendez** [comment]
You're right. Anyhow "swallows" the error produced by Tonic, the gRPC framework used in Rust for our case. While we're considering adding our own error pub Enum, it would be a breaking change.

The only way we know how to obtain the error from Anyhow is to downcast it, so for now, try the next:

```rs
if let Err(e) = client.upsert_points_blocking("not_found_collection", points, None).await {
    if let Some(te) = e.downcast_ref::<tonic::Status>() {
        println!("{:?}", te.code());
        println!("{:?}", te.message());
        println!("{:?}", te.metadata());
    }
}
```

We will consider adding this as a helper in the library, which would not be breaking but optional.

**Comment by ava57r** [comment]
Ok. Thanks.
