### ISSUE TITLE
example needs " on_disk:None" | else no compile

### ISSUE THREAD

**Issue by RGGH** [qdrant/rust-client#52]
eg:

`        vectors_config: Some(VectorsConfig {
                config: Some(Config::Params(VectorParams {
                    size: 10,
                    distance: Distance::Cosine.into(),
                    hnsw_config: None,
                    quantization_config: None,
                    ****on_disk:None****
                })),`

**Comment by agourlay** [comment]
Thank you for the report :+1: 

Fixed in https://github.com/qdrant/rust-client/commit/a58ec29adb6ab81bde4341cd1b6a949df01be80e
