### ISSUE TITLE
Issues connecting to Qdrant Cloud using client.

### ISSUE THREAD

**Issue by nicolasgarcia214** [qdrant/rust-client#61]
Hey,

I'm encountering errors while trying to use the `list_collections` method with the Qdrant Rust client. This error seems to be specific to the client as directly accessing the endpoint doesn't produce any issues.

**Here are the specifics:**

1. When I try to use port 6333, I receive the following error:

```rust
Err value: status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], 
metadata: MetadataMap { headers: {"server": "awselb/2.0", "date": "Tue, 25 Jul 2023 14:08:49 GMT", "content-length": "0"} }
 ```

2. When I switch to port 6334, I get a different error message:

```rust
Err value: status: Internal, message: "protocol error: received message with invalid 
compression flag: 52 (valid flags are 0 and 1)  while receiving response with status: 404 Not Found", details: [], 
metadata: MetadataMap { headers: {"server": "awselb/2.0", "date": "Tue, 25 Jul 2023 15:21:54 GMT", 
"content-type": "text/plain; charset=utf-8", "content-length": "19", "x-content-type-options": "nosniff"} }
```

I'm following the [search example](https://github.com/qdrant/rust-client/blob/master/examples/search.rs) but using Qdrant Cloud

Any insights or suggestions to address this would be greatly appreciated.

**Comment by agourlay** [comment]
The Rust client uses only the gRPC interface so you must stick to the `6334` port.

When talking to the cloud you also make sure to use `https` in the URL when configuring the client.

Which call is failing exactly?

**Comment by nicolasgarcia214** [comment]
Thanks for the quick reply. I just found out it was a typo in the URL
