### ISSUE TITLE
Local Qdrant 

### ISSUE THREAD

**Issue by DevinLeamy** [qdrant/rust-client#76]
Hi!

I'm curious whether there's any intention of adding support of a local qdrant setup for Rust, like there is for Python3. I would love to use qdrant for a project I'm working on and it would definitely be a huge convenience! 

```python3
from qdrant_client import QdrantClient
client = QdrantClient(path="path/to/db")  # Persists changes to disk, fast prototyping
```

Thanks for building this awesome database!

Cheers.

**Comment by timvisee** [comment]
Hi DevinLeamy,

No, we have no intention to add a local mode to the Rust client as well. That is because it would take a huge amount of work to implement this in every client.

**Comment by DevinLeamy** [comment]
> Hi DevinLeamy,
> 
> No, we have no intention to add a local mode to the Rust client as well. That is because it would take a huge amount of work to implement this in every client.

Okay, no worries! Thanks a bunch for building Qdrant!
