### ISSUE TITLE
Transport Error

### ISSUE THREAD

**Issue by hturner08** [qdrant/rust-client#82]
I have a Tauri (Rust) desktop app that uses a local qdrant for vector storage. Even after waiting for the gRPC channel message and a health check from the server I still get the following error when later in the code I'm trying to use my generated rust client object:
```
Err(status: Internal, message: "Failed to connect to http://localhost:6334/: transport error", details: [], metadata: MetadataMap { headers: {} })
```
Does anyone have any suggestions for what the issue might be? This only occurs on a subset of the machines I'm testing with.

**Comment by DennisJensen95** [comment]
I am also experiencing the same problem as you @hturner08. According to this thread https://github.com/qdrant/qdrant-helm/issues/112, it seems it was a cluster issue of 1.7.0, but I am running the qdrant cloud with version 1.7.3 and experiencing the same here as you for the rust client. 

Did you get a workaround for it?

**Comment by abhay-agarwal** [comment]
For future googlers -- I received this error when my rust client was not on the EXACT same version between client and server (in my case 1.10.1).
