### ISSUE TITLE
feature request: add seperate function for full-text-search for filters

### ISSUE THREAD

**Issue by densumesh** [qdrant/rust-client#85]
We are attempting to use qdrant's full text filters in order to be able to move our filtering logic to solely qdrant, however we were facing issues with the fact that qdrant's rust client only support full text matching when there is a space added to the end. 

We want to be able to use qdrant's full text and substring filtering as a replacement for the LIKE queries that we perform in pg as of rn, however, in certain cases where we have multi word filters or single word filters, the logic would behave unpredictably. 

Here is a link the the gist that contains our filtering logic: https://gist.github.com/skeptrunedev/3ede217aa78d6462c5c52c63d0318764. 

The easiest solution to this issue is probably adding a separate full text match function like python [does](https://qdrant.tech/documentation/concepts/filtering/#full-text-match). 

Thank you so much for a first class rust client and an amazing SVD!!

**Comment by Anush008** [comment]
Resolved with #86.
