### ISSUE TITLE
Implement configuration option for gzip compression

### ISSUE THREAD

**Issue by generall** [qdrant/rust-client#96]
Currently, Qdrant server gRPC is able to receive and send gzip-ed traffic.
But in order to use this functionality, it should be also enabled on the client.

We should create an option on the client builder, which should allow us to enabled compressed traffic to the server.

Reference - https://docs.rs/tonic/latest/tonic/client/struct.Grpc.html#method.send_compressed

**Comment by GodTamIt** [comment]
@generall this was done by #99 so I think it can be closed :)

**Comment by timvisee** [comment]
Thanks!
